FriendsOfSylius/SyliusImportExportPlugin

README.md, src/DependencyInjection/Compiler/RegisterImporterPass.php, src/DependencyInjection/FOSSyliusImportExportExtension.php, src/FOSSyliusImportExportPlugin.php, tests/Application/app/AppKernel.php, tests/Application/app/config/routing.yml
fixes https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/27
=> prefix bundle/extension with FOS

composer.json, features/cli/importing_countries_from_csv_via_cli.feature, features/cli/importing_countries_from_excel_via_cli.feature, features/cli/importing_payment_methods_from_csv_via_cli.feature, features/cli/importing_payment_methods_from_excel_via_cli.feature, features/cli/importing_tax_categories_from_csv_via_cli.feature, features/cli/importing_tax_categories_from_excel_via_cli.feature, spec/Importer/CountriesImporterSpec.php, spec/Importer/PaymentMethodsImporterSpec.php, spec/Importer/TaxCategoriesImporterSpec.php, src/Command/ImportDataCommand.php, src/Controller/ImportDataController.php, src/Exception/ItemIncompleteException.php, src/Importer/AbstractImporter.php, src/Importer/CountriesImporter.php, src/Importer/ImporterInterface.php, src/Importer/ImporterResult.php, src/Importer/PaymentMethodsImporter.php, src/Importer/TaxCategoriesImporter.php, tests/Behat/Context/NotificationContext.php
fixed #9 
missing testing of returned `ImportResult` instance
=> added result meta data

src/Controller/ImportDataController.php, src/DependencyInjection/Compiler/RegisterImporterPass.php, src/Form/ImportType.php, src/Resources/config/services.yml, src/Resources/views/Crud/import.html.twig, src/Resources/views/Crud/import_form.html.twig, tests/Behat/Page/ResourceIndexPage.php
fixes https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/24
=> implement form component for upload form

README.md
=> fixes #33 - composer install before tests

features/ui/importing_tax_categories_from_csv.feature, features/ui/importing_tax_categories_from_excel.feature, spec/DependencyInjection/Compiler/RegisterImporterPassSpec.php, spec/Importer/ResourceImporterSpec.php, src/DependencyInjection/Compiler/RegisterImporterPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/FOSSyliusImportExportExtension.php, src/Importer/ResourceImporter.php, src/Resources/config/services.yml, src/Resources/config/services_csv.yml, src/Resources/config/services_excel.yml, tests/Behat/Context/TaxCategoriesContext.php
missing some additional tests ..
rollback on failure option might also make sense .. though of course in case a batch size is configured, it might not be possible to rollback everything anymore.
=> [WIP] add config options for web_ui, batch_size, fail_on_incomplete, stop_on_failure

README.md
=> add configuration documentation

src/DependencyInjection/Configuration.php, tests/Application/.gitignore, tests/Application/app/config/config.yml, tests/Application/app/config/config_prod.yml, tests/Application/package.json
=> Update files with changes from sylius/plugin-skeleton v1.0.9

README.md
Added installation step 'Add plugin dependencies to your AppKernel.php file' to Readme.md
=> Added installation step 'Add plugin dependencies'

composer.json
I asked to get stable releases and got them quickly :)
=> use stable versions of portphp

composer.json
due to regression caused by https://github.com/symfony/symfony/commit/c026ec63e33c696c422f3d72c99c8fe64f091376#diff-f7b23d463cba27ac5e4cb677f2be7623R985
https://travis-ci.org/FriendsOfSylius/SyliusImportExportPlugin/jobs/348897843#L923
=> set a conflict on Symfony v3.4.5, fixes #54

spec/DependencyInjection/Compiler/RegisterExporterPassSpec.php, spec/Listener/ExportButtonGridListenerSpec.php, src/DependencyInjection/Compiler/RegisterExporterPass.php, src/Listener/ExportButtonGridListener.php
Not that easy to test currently (https://github.com/Sylius/Sylius/issues/9271), but I think this does the job for now.
=> [Export] Add spec for export button grid listener

features/export/ui/export_links_on_countries_grid.feature, features/import/ui/importing_countries_from_csv.feature, features/import/ui/importing_countries_from_excel.feature, src/Resources/config/services_csv.yml, tests/Behat/Context/CountriesContext.php, tests/Behat/Resources/services.xml
First features to check links in admin grid.
=> [Export] Add feature tests for export UI on countries (first merge #78)

README.md, spec/Exporter/ResourceExporterSpec.php, spec/Exporter/Transformer/Handler/DateTimeToStringHandlerSpec.php, spec/Exporter/Transformer/Handler/IntegerToMoneyFormatHandlerSpec.php, spec/Exporter/Transformer/PoolSpec.php, src/Exporter/Plugin/PluginPool.php, src/Exporter/Plugin/ResourcePlugin.php, src/Exporter/ResourceExporter.php, src/Exporter/Transformer/Handler.php, src/Exporter/Transformer/Handler/DateTimeToStringHandler.php, src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php, src/Exporter/Transformer/HandlerInterface.php, src/Exporter/Transformer/Pool.php, src/Exporter/Transformer/TransformerPoolInterface.php, src/Resources/config/services.yml, src/Resources/config/services_csv.yml
Currently only 'DateTime' -> string as default & one that adjusts Numeric values to money format for specific fields (currently only the 'Total' field as used in Orders).
=> Exporter field transformers before writing data to file

.travis.yml, src/Controller/ImportDataController.php
As discussed on Slack, @lsmith77.
=> Re-add easy-coding-standard checks in Travis CI

README.md, phpstan.neon, spec/DependencyInjection/Compiler/RegisterExporterPassSpec.php, spec/Listener/ExportButtonGridListenerSpec.php, src/Controller/ExportDataController.php, src/DependencyInjection/Compiler/RegisterExporterPass.php, src/Listener/ExportButtonGridListener.php, src/Resources/config/routing.yml, src/Resources/config/services.yml, src/Resources/config/services_export_csv.yml, src/Resources/config/services_export_excel.yml
Takes criteria from URL GET and passes them to exporter controller, using resource resolving similar to Sylius' ResourceController. Needs tests, features, and more testing.
Also have an issue as mentioned in #80 where the default criteria returns 0 results because the 'enabled' filter seems not be behave properly. It returns data on the grid itself, but in the export the result is zero..
=> [Export] [WIP] Add exporter for ui grid criteria (first merge #79)

.gitignore, composer.lock
https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/113#issuecomment-394172887
=> Add composer.lock to fix scrutinizer

composer.json, composer.lock
made some initial steps, interested in getting comments
=> implementing enqueue bundle

composer.json, composer.lock
relates to #120 and relates to #8 
recreates https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/115 which was lost during a rebase mistake
=> initial steps to support message queue

src/Command/ExportDataCommand.php, src/Command/ExportDataToMessageQueueCommand.php, src/Command/ImportDataCommand.php, src/Command/ImportDataFromMessageQueueCommand.php
basically we return void, which results in exit code 0 or we throw an exception which results in a non zero exit code.
=> use exceptions for non zero exit code

README.md, src/Processor/ResourceProcessor.php
or make it great again
fixes #130 and is needed for #131
=> make import more dynamic

README.md, src/Resources/config/services.yml, src/Resources/config/services_import_csv.yml, src/Resources/config/services_import_excel.yml, src/Resources/config/services_import_json.yml
Excel and CSV can be looked at in another PR
partly fixes #20 ~~will open a new issue when this one is closed~~ -> opened
=> add customer JSON import 

.travis.yml, composer.json, composer.lock, src/DependencyInjection/Compiler/RegisterExporterPass.php, src/DependencyInjection/Compiler/RegisterImporterPass.php, src/Resources/config/services.yml, tests/Application/app/config/config.yml
Added support for Symfony 4.1. Issue #143
=> Support for Symfony 4.1

src/Resources/translations/messages.nl.yml
=> Added dutch translations

features/export/ui/export_check_ids.feature, src/Resources/config/services_export_csv.yml, tests/Behat/Context/CliBaseContext.php
=> set comma to default csv delimiter

features/export/ui/export_check_ids.feature
=> [Behat]  remove identifiers in tests

README.md, spec/Importer/JsonResourceImporterSpec.php, spec/Processor/PaymentMethodProcessorSpec.php, spec/Processor/ResourceProcessorSpec.php, src/DependencyInjection/Configuration.php, src/Importer/JsonResourceImporter.php, src/Importer/ResourceImporter.php, src/Processor/PaymentMethodProcessor.php, src/Processor/ResourceProcessor.php, src/Resources/config/services.yml
Fixes #186 
I put `batch_size` by default to 1, for flush after each item.
=> fix batching logic for processors

README.md, spec/Controller/ExportDataControllerSpec.php, spec/Controller/ImportDataControllerSpec.php, src/Controller/ExportDataController.php, src/Controller/ImportDataController.php, src/DependencyInjection/ParameterBag/ParameterBag.php, src/Resources/config/routing.yml, src/Resources/config/services.yml
Feature for "Define controllers as services" #91
=> set controller as service

spec/DependencyInjection/Compiler/RegisterExporterPassSpec.php, src/DependencyInjection/Compiler/RegisterExporterPass.php, src/Listener/ExportButtonGridListener.php, src/Resources/config/routing.yml
If we use custom exporter this "Backup route" catch page call and make an fatal error.
So i fixed by using spéficic route for each export.
This not a BC, because app_export_data_*  respect the format used and described in the doc.
=> fix routing for custom export

src/Controller/ImportDataController.php, src/Form/ImportType.php, src/Resources/views/Crud/import_form.html.twig, src/Resources/views/Form/theme.html.twig, tests/Behat/Page/ResourceIndexPage.php
| Fixed tickets | 
Update UI on Admin interface :
- Transforming Exceptions into Error Messages
- Add new style to import form
For Sylius <1.6
=> improve ui

features/import/cli/detecting_file_extension_for_cli.feature, src/Command/ImportDataCommand.php, tests/Behat/Context/CliBaseContext.php, tests/Behat/Resources/services.xml, tests/Behat/Resources/suites.yml
| New feature?  | yes
| Fixed tickets | #206
Auto detect file format to make the --format parameter optional.
=> auto detect file format

.github/CODEOWNERS
=> add oallain to codeowners

.github/CODEOWNERS, composer.json, src/Exporter/Plugin/ProductResourcePlugin.php, src/Importer/JsonResourceImporter.php, src/Processor/ProductProcessor.php, tests/Application/yarn.lock
| New feature?  | yes
| Fixed tickets | #... 
Throw a new exception if content contain null by json_decode return
=> Check if json content is valid

README.md, src/Command/ExportDataCommand.php, src/Command/ExportDataToMessageQueueCommand.php, src/Command/ImportDataCommand.php, src/Command/ImportDataFromMessageQueueCommand.php, src/DependencyInjection/Compiler/RegisterImporterPass.php
| New feature?  | yes
| Fixed tickets | #220 , #160 
Allow to import/export custom ressources (not sylius.* ressource).
=> Custom ressource

src/Exporter/Plugin/OrderResourcePlugin.php
| Fixed tickets | #211 
The exported grid didn't display every information. Please review it and get back to me when possible !
=> Modifying the OrderResourcePlugin to display correct data

README.md
We have remove scrutinizer to CI but not in Readme.
=> Remove scrutinizer to readme

src/Resources/translations/messages.fr.yml
| Fixed tickets | #229
Add missing french translations
=> Add french translations

README.md
=> Update README.md for Symfony 4+

composer.json, tests/Application/config/bundles.php, tests/Application/config/packages/dev/swiftmailer.yaml, tests/Application/config/packages/mailer.yaml, tests/Application/config/packages/staging/swiftmailer.yaml, tests/Application/config/packages/swiftmailer.yaml, tests/Application/config/packages/test/mailer.yaml, tests/Application/config/packages/test/swiftmailer.yaml, tests/Application/config/packages/test_cached/mailer.yaml, tests/Application/config/packages/test_cached/swiftmailer.yaml
1.12 changed thing with swiftmailer and symfony/mailer so the build is now broken
=> Test build fix for master

spec/Exporter/ResourceExporterSpec.php, spec/Exporter/Transformer/Handler/ArrayToStringHandlerSpec.php, spec/Exporter/Transformer/Handler/DateTimeToStringHandlerSpec.php, spec/Exporter/Transformer/Handler/IntegerToMoneyFormatHandlerSpec.php, spec/Exporter/Transformer/PoolSpec.php, spec/Importer/JsonResourceImporterSpec.php, spec/Importer/ResourceImporterSpec.php, src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php, src/Resources/config/services.yml
I don't know phpspec and don't get the failures.. i will just fix twig deprecations for now :)
=> Enable spec

.github/workflows/build.yml, composer.json, tests/Application/config/bundles.php
PR to add support of sylius 1.13
=> support of sylius 1.13
