FriendsOfSylius/SyliusImportExportPlugin

- src/Resources/views/Crud/import_form.html.twig
- tests/Behat/Page/ResourceIndexPage.php
Applies some basic styling to the import form so it feels more naturally part of the Sylius admin UI.
Before:
After:
> Style import form so it fits Sylius admin UI

- src/Controller/ImportDataController.php
If you are using the ImportExport Plugin for custom resources e.g. suppliers, the route names usually won't have the prefix `sylius_admin_` . So maybe it's better to redirect to the referer
> Redirect to referer instead of building route programmatically

- spec/Exporter/Plugin/PluginPoolSpec.php
- spec/Exporter/Plugin/ResourcePluginSpec.php
- src/Exporter/Plugin/PluginFactory.php
- src/Exporter/Plugin/PluginFactoryInterface.php
- src/Exporter/Plugin/PluginInterface.php
- src/Exporter/Plugin/PluginPool.php
- src/Exporter/Plugin/ResourcePlugin.php
- src/Exporter/Plugin/ResourcePluginInterface.php
- src/Exporter/ResourceExporter.php
Use case: I created an Order export, with a field name that didn't exist at all (OrderNumber, it should be Number), which just resulted in an empty column in the export file. This change checks more strict whether the defines keys are actually being filled in order to avoid unexpected behavior.
> Be more strict on exported field names - fields should exist

- src/Controller/ExportDataController.php
- src/Exporter/ResourceExporter.php
- src/Exporter/ResourceExporterInterface.php
- src/Writer/CsvWriter.php
- src/Writer/WriterInterface.php
When not setting a filename for the `CsvWriter` a `php://temp` stream is being used, which is being emptied at the end of the request or when not needed anymore. This allows us to even simplify fetching of the data regardless of whether a filename has been set, because the stream is available. Still allows for customisation.
> Use php temp stream as default for exporting (closes #89)

- src/Command/ExportDataCommand.php
- Added concatenation of 'sylius.' with the exporter as the exporter got renamed and needs a sylius infront now.
- Since the exporter has sylius infront now we have to ignore the first field of $exporter[]
> CLI export fix

- README.md
- composer.json
- composer.lock
- src/Command/ExportDataToMessageQueueCommand.php
- src/Command/ImportDataCommand.php
- src/Command/ImportDataFromMessageQueueCommand.php
- src/Exporter/ItemReaderInterface.php
- src/Exporter/ItemWriterInterface.php
- src/Exporter/MqItemReader.php
- src/Exporter/MqItemWriter.php
- src/Exporter/ResourceExporter.php
- src/Exporter/ResourceExporterInterface.php
- src/Importer/JsonResourceImporter.php
- src/Importer/SingleDataArrayImporterInterface.php
- src/Resources/config/services.yml
fixes #8 
note this doesn't yet provide abstraction to use different MQ systems. atm only Redis is supported. (see https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/127)
also note that the exit code handling in the commands should be updated in https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/126 once this is merged
> Message queue support

- src/Exporter/MqItemReader.php
removed it simply because this is makes data that wants to be imported need to have an `id` field.. it could potentially remade differently in another PR
> remove date check on import

- src/Listener/ExportButtonGridListener.php
When using this bundle with [PHP-PM](https://github.com/php-pm/php-pm), the `ExportButtonGridListener` service is initialized only once, so the `$links` attribute is only populated in the first request. This PR fixes this by repopulating the links array every time the grid event occurs.
> Do not use internal storage for export links

- README.md
- src/DependencyInjection/Configuration.php
With the config example in the README : `batch_size : false` we get this error :
```
In IntegerNode.php line 29:
Invalid type for path "fos_sylius_import_export.importer.batch_size". Expected int, but got boolean.  
```
> Fix install with batch_size : 0

- src/DependencyInjection/Compiler/MessageQueuePass.php
If we don't need to use the message queue and don't configure `fos_sylius_import_export.message_queue.service_id` as suggested in the README, we met this error : 
```
In Reference.php line 24:
Argument 1 passed to Symfony\Component\DependencyInjection\Reference::__construct() must be of the type string, null given, called in /var/www/html/vendor/friendsofsylius/sylius-import-exp  
ort-plugin/src/DependencyInjection/Compiler/MessageQueuePass.php on line 21                                                                                                                   
```
This PR fix this
> Fix install without sylius.message_queue

- spec/Exporter/Plugin/OrderResourcePluginSpec.php
- spec/Exporter/Plugin/ResourcePluginSpec.php
- src/Exporter/Plugin/ResourcePlugin.php
We came across an issue caused by using column names instead of field names while exporting taxons. The taxon has the `right` field, which is mapped as `tree_right` column. This makes the property accessor trying to get `treeRight` property or call `getTreeRight` method which does not exist and the export crashes.
> Use field names instead of column names

- src/Exporter/Plugin/ProductResourcePlugin.php
- src/Processor/ProductProcessor.php
| Fixed tickets | 
Fixes for PHPStan issues :
```
------ ----------------------------------------------- 
Line   Exporter/Plugin/ProductResourcePlugin.php      
------ ----------------------------------------------- 
138    Cannot call method getPrice() on object|null.  
------ ----------------------------------------------- 
------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Line   Processor/ProductProcessor.php                                                                                                                                              
------ …
```
> fix ChannelInterface and ChannelPricingInterface types

- src/Controller/ExportDataController.php
Add the content type to header for correct file format download
| Fixed tickets | #165  
Fix the bad .html extension when download exported file from Web UI
> Add content type to header

- composer.json
| Fixed tickets | #237 
Update the dependency of the Symfony Stopwatch component (thanks to @andychan94) to add support for Symfony 4.4.
> Support for Symfony 4.4

- src/Resources/config/services.yml
| Fixed tickets | #253
Hard-coding the ProductImage model class breaks default setups where the entity is actually `App\Entity\Product\ProductImage`.
The default in Sylius apparently is to always use parameters where models are involved.
> Use Sylius parameter for product image model

- .github/workflows/build.yml
- composer.json
- phpunit.xml.dist
| New feature?  | yes
| Fixed tickets | #263 
Add Sylius 1.10 support.
> Add Sylius 1.10 support

- README.md
- src/DependencyInjection/Compiler/RegisterImporterPass.php
Added option to use 'domain' in service config tag so instead of type taking the value "app.foo" you will use "type: foo" and "domain: app"
This fixes the selection of export format in the admin interface.
| Fixed tickets | #249
> Make service config a bit more flexible

- spec/Controller/ImportDataControllerSpec.php
- src/Controller/ImportDataController.php
- src/Resources/views/Form/theme.html.twig
Since Twig 2.7 these feature has been deprecated and now can safely be used as minimal dependency is 2.11 for this package.
> Fix twig deprecations

- composer.json
| Fixed tickets | https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/287
I'm not sure why there's a conflict with API platform but it's a problem with API 1.12 and in the future, 1.13.
2.6.* works but 2.7.* should be allowed to prepare future upgrades.
Edit : damn that's my own mistake :D
> Conflict with api platform prevent upgrades

- src/Resources/views/Crud/import.html.twig
- src/Resources/views/Taxonomy/import.html.twig
| Fixed tickets | #290
Use the proper Twig render `controller(...)` statement (using double semicolon instead of only one semicolon for defining the controller action method).
> Use proper Twig controller render statement

- src/Resources/config/routing.yml
| BC breaks?   | yes/no ?
| Fixed tickets | #... 
Fix 
> The controller for URI "/admin/export/sylius.order/csv" is not callable: Controller "sylius.controller.export_data_order:exportAction" does neither exist as service nor as class.
Error.
> Fix controller definitions

- src/Listener/ExportButtonGridListener.php
| Fixed tickets | none
This change allows non scalar values to be used through the criteria : filters passed bu Sylius Grid.
This is needed for most filters, including plain text search : ?criteria[search][type]=contains&criteria[search][value]=test
> allow non scalar values for criteria
